// Automatically generated by forge bind-json.
pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {EIP712Types} from 'tests/helpers/EIP712Types.sol';

interface Vm {
  function parseJsonTypeArray(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function serializeJsonType(
    string calldata typeDescription,
    bytes memory value
  ) external pure returns (string memory json);

  function serializeJsonType(
    string calldata objectKey,
    string calldata valueKey,
    string calldata typeDescription,
    bytes memory value
  ) external returns (string memory json);
}

library JsonBindings {
  Vm constant vm = Vm(address(uint160(uint256(keccak256('hevm cheat code')))));

  // prettier-ignore
  string constant schema_BuyAssetWithSig = "BuyAssetWithSig(address originator,uint256 minAmount,address receiver,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SellAssetWithSig = "SellAssetWithSig(address originator,uint256 maxAmount,address receiver,uint256 nonce,uint256 deadline)";

  function serialize(
    EIP712Types.BuyAssetWithSig memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_BuyAssetWithSig, abi.encode(value));
  }

  function serialize(
    EIP712Types.BuyAssetWithSig memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_BuyAssetWithSig, abi.encode(value));
  }

  function deserializeBuyAssetWithSig(
    string memory json
  ) public pure returns (EIP712Types.BuyAssetWithSig memory) {
    return
      abi.decode(vm.parseJsonType(json, schema_BuyAssetWithSig), (EIP712Types.BuyAssetWithSig));
  }

  function deserializeBuyAssetWithSig(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.BuyAssetWithSig memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_BuyAssetWithSig),
        (EIP712Types.BuyAssetWithSig)
      );
  }

  function deserializeBuyAssetWithSigArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.BuyAssetWithSig[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_BuyAssetWithSig),
        (EIP712Types.BuyAssetWithSig[])
      );
  }

  function serialize(
    EIP712Types.SellAssetWithSig memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SellAssetWithSig, abi.encode(value));
  }

  function serialize(
    EIP712Types.SellAssetWithSig memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_SellAssetWithSig, abi.encode(value));
  }

  function deserializeSellAssetWithSig(
    string memory json
  ) public pure returns (EIP712Types.SellAssetWithSig memory) {
    return
      abi.decode(vm.parseJsonType(json, schema_SellAssetWithSig), (EIP712Types.SellAssetWithSig));
  }

  function deserializeSellAssetWithSig(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SellAssetWithSig memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SellAssetWithSig),
        (EIP712Types.SellAssetWithSig)
      );
  }

  function deserializeSellAssetWithSigArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SellAssetWithSig[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SellAssetWithSig),
        (EIP712Types.SellAssetWithSig[])
      );
  }
}
