use strata_db_types::DbError;
use strata_identifiers::SubjectId;
use strata_primitives::l2::L2BlockCommitment;
use thiserror::Error;

pub type EngineResult<T> = Result<T, EngineError>;

#[derive(Debug, Error)]
pub enum EngineError {
    #[error("unknown payload ID {0}")]
    UnknownPayloadId(u64),

    #[error("amount conversion sats: {0}")]
    AmountConversion(u64),

    #[error("invalid address {0}")]
    InvalidAddress(SubjectId),

    #[error("db: {0}")]
    Db(#[from] DbError),

    #[error("invalid payload in block {0:?}")]
    InvalidPayload(L2BlockCommitment),

    #[error("missing required dependency: {0}")]
    MissingDependency(&'static str),

    #[error("not yet implemented")]
    Unimplemented,

    #[error("{0}")]
    Other(String),

    /// Generated by the worker handle when the worker has exited before being
    /// able to process a message we were trying to send.
    #[error("engine worker exited")]
    WorkerExited,
}
