name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    env:
      ETHEREUM_NODE_MAINNET: ${{ secrets.ETHEREUM_NODE_MAINNET }}
      ETHEREUM_NODE_ARBITRUM: ${{ secrets.ETHEREUM_NODE_ARBITRUM }}
      ETHEREUM_NODE_BASE: ${{ secrets.ETHEREUM_NODE_BASE }}
      ETHEREUM_NODE_PLUME: ${{ secrets.ETHEREUM_NODE_PLUME }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes --build-info --skip './test/**'
        id: build

      - name: Run Slither
        uses: crytic/slither-action@v0.4.2
        with:
          fail-on: all
          ignore-compile: true

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
