// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           60
// Async Callback:                       1
// Promise callbacks:                    6
// Total number of exported functions:  69

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        delegate => delegate
        unDelegate => un_delegate
        withdraw => withdraw
        getLsValueForPosition => get_ls_value_for_position
        getEgldPositionValue => get_egld_position_value
        getExchangeRate => get_exchange_rate
        getDelegationContractStakedAmount => get_delegation_contract_staked_amount
        getDelegationContractUnstakedAmount => get_delegation_contract_unstaked_amount
        registerLsToken => register_ls_token
        registerUnstakeToken => register_unstake_token
        setStateActive => set_state_active
        setStateInactive => set_state_inactive
        setAccumulatorContract => set_accumulator_contract
        setFees => set_fees
        setMaxAddresses => set_max_addresses
        setMaxSelectedProviders => set_max_selected_providers
        setUnbondPeriod => set_unbond_period
        addManagers => set_managers
        removeManager => remove_manager
        addLiquidityProvider => add_liquidity_provider
        removeLiquidityProviders => remove_liquidity_provider
        setScoringConfig => set_scoring_config
        delegatePending => delegate_pending
        unDelegatePending => un_delegate_pending
        withdrawPending => withdraw_pending
        claimRewards => claim_rewards
        claimFees => claim_fees
        getDelegationAddressesList => delegation_addresses_list
        getUnDelegationAddressesList => un_delegation_addresses_list
        getDelegationContractInfo => delegation_contract_data
        getManagers => managers
        getLiquidityProviders => liquidity_providers
        getScoringConfig => scoring_config
        fees => fees
        getAccumulatorContract => accumulator_contract
        getState => state
        getLsTokenId => ls_token
        getLsSupply => ls_token_supply
        getVirtualEgldReserve => virtual_egld_reserve
        getFeesReserve => fees_reserve
        getTotalWithdrawnEgld => total_withdrawn_egld
        getUnstakeTokenId => unstake_token
        getPendingEGLDForDelegate => pending_egld
        getPendingEGLDForUnDelegate => pending_egld_for_unstake
        getPendingEgldForUnbond => pending_egld_for_unbond
        getUnstakeTokenNonce => unstake_token_nonce
        maxDelegationAddresses => max_delegation_addresses
        maxSelectedProviders => max_selected_providers
        unbondPeriod => unbond_period
        migrate => migrate
        migratePending => migrate_pending
        addRewards => add_rewards
        setMigrationScAddress => add_migration_sc_address
        getMigrationScAddress => migration_sc_address
        whitelistDelegationContract => whitelist_delegation_contract
        changeDelegationContractAdmin => change_delegation_contract_admin
        changeDelegationContractParams => change_delegation_contract_params
        set_vote_contract => set_vote_contract
        delegateVote => delegate_vote
        getVoteContract => vote_contract
        remove_liquidity_callback => remove_liquidity_callback
        add_liquidity_callback => add_liquidity_callback
        withdraw_tokens_callback => withdraw_tokens_callback
        claim_rewards_callback => claim_rewards_callback
        whitelist_delegation_contract_callback => whitelist_delegation_contract_callback
        instant_delegation_contract_callback => instant_delegation_contract_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
