[package]
name = "deri"
version = "1.0.0"
authors = []

[addresses]
deri = "_"
admin = "_"
protocol_fee_manager = "_"
liq_claim = "_"

[dev-addresses]

[dependencies]
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }
AptosTokenObjects = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "dev" }

[dev-dependencies]
