// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    flash_mock
    (
        init => init
        upgrade => upgrade
        flash => flash
        flashRepaySome => flash_repay_some
        flashRepaySomeWrongToken => flash_repay_some_wrong_token
        flashNoRepay => flash_no_repay
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
