// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           26
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_layer
    (
        init => init
        upgrade => upgrade
        updateParams => update_params
        getSuppliedScaled => supplied
        getRevenueScaled => revenue
        getBorrowedScaled => borrowed
        getParameters => parameters
        getBorrowIndex => borrow_index
        getSupplyIndex => supply_index
        getLastTimestamp => last_timestamp
        updateIndexes => update_indexes
        supply => supply
        borrow => borrow
        withdraw => withdraw
        repay => repay
        addRewards => add_reward
        flashLoan => flash_loan
        createStrategy => create_strategy
        seizePosition => seize_position
        claimRevenue => claim_revenue
        capitalUtilisation => capital_utilisation
        reserves => reserves
        depositRate => deposit_rate
        borrowRate => borrow_rate
        deltaTime => delta_time
        protocolRevenue => protocol_revenue
        suppliedAmount => supplied_amount
        borrowedAmount => borrowed_amount
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
