// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    price_aggregator
    (
        init => init
        upgrade => upgrade
        submit => submit
        submitBatch => submit_batch
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        submission_count => submission_count
        latestRoundData => latest_round_data
        latestPriceFeed => latest_price_feed
        getOracles => get_oracles
        addOracles => add_oracles
        removeOracles => remove_oracles
        setSubmissionCount => set_submission_count
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
