[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
evm_version = "shanghai"

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = false
remappings_location = "txt"

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.0.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
